export const dataProducts = [
  {
    id: 1,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },

  {
    id: 2,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
  {
    id: 3,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
  {
    id: 4,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
  {
    id: 5,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
  {
    id: 6,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
  {
    id: 7,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
  {
    id: 8,
    name: "Pizza 1",
    price: 59.99,
    description: "Nintendo Switch",
    quality: 1,
    categoryName: "pizza",
    linkImg: "/images/pizza/p5.PNG",
  },
];
